### ISSUE TITLE
command already defined

### ISSUE THREAD

**Issue by Wccurate** [geekplux/cv_resume#11]
在macOS和Windows编译遇到了相同的问题如下：
! LaTeX Error: Command \makecvtitlenamewidth already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.101 \newlength{\makecvtitlenamewidth}

? x
No pages of output.
Transcript written on template_cn_blue.log.
mingw32-make: *** [Makefile:2: all] Error 1

**Comment by Hunter9812** [comment]
可以删除根目录的[moderncvstyleclassic.sty]解决

**Comment by Wccurate** [comment]
> 可以删除根目录的[moderncvstyleclassic.sty]解决

谢谢佬，有用的！
