### ISSUE TITLE
大佬右上角字体怎么设置啊

### ISSUE THREAD

**Issue by sssomeone** [geekplux/cv_resume#2]
![](https://blog.mysakure.com//img/2019-12-03%2001-02-54%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by geekplux** [comment]
你看看 tex 文件里的哪个字体你系统里没有，安装一下

**Comment by sssomeone** [comment]
> 你看看 tex 文件里的哪个字体你系统里没有，安装一下


Package fontspec Info: Could not resolve font "Times New Roman/BI" (it
(fontspec)             probably doesn't exist).


Package fontspec Info: Could not resolve font "Times New Roman/B" (it probably
(fontspec)             doesn't exist).


Package fontspec Info: Could not resolve font "Times New Roman/I" (it probably
(fontspec)             doesn't exist).
大佬报错是这个，但是我知道这个字体我安装了，但是调用貌似是错误的

**Comment by sssomeone** [comment]
![](https://blog.mysakure.com/img/2019-12-03%2009-35-40%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)
大佬这几个类型的是有的，但是貌似调用出错了，怎么解决啊

**Comment by geekplux** [comment]
你看看它找字体的路径？
